### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pekkavaa** [joope/yspeli#3]
- [x] pelaajan nimen näyttö + syöttö
- [x] tiimin valinta
- [x] flash messaget jotka voi lisätä jollain `flashMessage(message, interval)`
- [x] clientin joystick näkyviin
- [x] hostin PLAY-nappula joka aloittaa pelin
- [x] automaattinen aloitus esim. 30 sek päästä
- [x] countdown timer joka näkyy
- [ ] eri näköiset autot
- [x] EMOJIAUTOT :joy_cat::ok_hand:
- [x] pelihuoneet, default pelihuone
- [ ] piilota pallo tiiminvalinnassa
- [ ] pelaajien nimet talteen local storageen clientissä
- [ ] pelaajien info formi, tsekkaus
- [ ] yleistä UI fiksausta

ideoita:
- [x] pelaajien kimpoaminen reunoista
- [ ] testaa onko hauskaa: pelaajien törmäys toisistaan
- [ ] tee ohjauksesta automaisempi: ohjaussuunnan interpolointi
- [ ] maalintekijän träkkäys ja näyttö kun maali tehdään
- [ ] myös omat maait

bugit:
- [ ] pallo pääsee maalin sisään warmupin aikana
- [ ] fiksaa STATE_PARTY

deprekoitu:
- [ ] vendoroi howler.js että peli toimii lanissa
